### ISSUE TITLE
Alpine 3.7

### ISSUE THREAD

**Issue by epistrephein** [JoeNyland/docker-ruby-alpine-libv8#2]
I was trying to recreate your steps of installing libv8 on the new Alpine 3.7, but I systematically get errors building the gem.
Is there any way you can update this to 3.7? Or guide me in any direction to be able to do it myself?

**Comment by JoeNyland** [comment]
Hey @epistrephein,

I'm not sure what error you're getting when you've attempted to install `libv8` on Alpine 3.7. When I try to `gem install libv8 -v 3.16.14.16` on `ruby:2.3-alpine3.7`, I get a `Segmentation fault` which has already been reported under #1.

I wish I could help you out, but unfortunately I don't really have any expertise to be able to dig into why this segfault is happening on this version of Alpine. The issue is somewhere between the `libv8` gem and Alpine 3.7. So, I said in #1 I can only recommend you raise an issue at https://github.com/cowboyd/libv8/issues and ask for help there. Hopefully they will be able to help in some way!
